### ISSUE TITLE
goslate tenta instalar futures e instalação falha

### ISSUE THREAD

**Issue by xisberto** [marcelomdevasconcellos/emensageria#28]
Tentativa de executar pip install falha com a mensagem:

```
Collecting futures
Downloading futures-3.0.5.tar.gz (25 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/humberto.fraga/local/emensageria/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
          from setuptools.dist import Distribution
        File "/home/humberto.fraga/local/emensageria/venv/lib/python3.10/site-packages/setuptools/dist.py", line 32, in <module>
          from setuptools.extern.more_itertools import unique_everseen
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 571, in module_from_spec
        File "/home/humberto.fraga/local/emensageria/venv/lib/python3.10/site-packages/setuptools/extern/__init__.py", line 52, in create_module
          return self.load_module(spec.name)
        File "/home/humberto.fraga/local/emensageria/venv/lib/python3.10/site-packages/setuptools/extern/__init__.py", line 37, in load_module
          __import__(extant)
        File "/home/humberto.fraga/local/emensageria/venv/lib/python3.10/site-packages/setuptools/_vendor/more_itertools/__init__.py", line 1, in <module>
          from .more import *  # noqa
        File "/home/humberto.fraga/local/emensageria/venv/lib/python3.10/site-packages/setuptools/_vendor/more_itertools/more.py", line 5, in <module>
          from concurrent.futures import ThreadPoolExecutor
        File "/tmp/pip-install-nw1ru0wk/futures_c5077efa096b44258117dd76a873bb6b/concurrent/futures/__init__.py", line 8, in <module>
          from concurrent.futures._base import (FIRST_COMPLETED,
        File "/tmp/pip-install-nw1ru0wk/futures_c5077efa096b44258117dd76a873bb6b/concurrent/futures/_base.py", line 357
          raise type(self._exception), self._exception, self._traceback
                                     ^
      SyntaxError: invalid syntax
      [end of output]
```

Investigando a instalação que já temos, vi que o futures é instalado como dependêcia dos pacotes abaixo:

```
goslate==1.5.1
  - futures [required: Any, installed: 2.2.0]
libesocial==0.0.1rc1
    - eight [required: >=0.3.0,<1, installed: 0.4.2]
      - future [required: >=0.16,<0.17, installed: 0.16.0]
```

O goslate está com um aviso em sua página dizendo que não mais funciona: https://pypi.org/project/goslate. Removendo esta dependência, o build ocorreu com sucesso. Ela ainda é utilizada em alguma parte do sistema? Pode ser feito algo para eliminar seu uso?

**Comment by marcelomdevasconcellos** [comment]
Você não terá problemas em não instalar ela. Eu removi a dependência do requirements.txt, era uma dependência antiga que traduzia os erros contidos no XML, não estava mais sendo utilizada. Muito obrigado pelo retorno!

**Comment by xisberto** [comment]
Ok, obrigado pela informação!
