### ISSUE TITLE
Não foi possível ler o arquivo /Users/...

### ISSUE THREAD

**Issue by xisberto** [marcelomdevasconcellos/emensageria#3]
Ao tentar enviar um evento para o eSocial, foi exibido o erro abaixo:

```
Internal Server Error: /esocial/enviar-evento/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/./apps/esocial/views.py", line 130, in enviar_evento
    response = evt.enviar()
  File "/app/./apps/esocial/models.py", line 897, in enviar
    return tra_evt.enviar()
  File "/app/./apps/esocial/models.py", line 308, in enviar
    save_file(dados['request'], self.make_send())
  File "/app/./apps/esocial/models.py", line 238, in make_send
    str(self.eventos()))
  File "/app/./apps/esocial/models.py", line 225, in eventos
    read_file(evt.xml_file()))
  File "/app/./config/functions.py", line 34, in read_file
    raise NameError('Não foi possivel ler o arquivo %s.' % filename)
NameError: Não foi possivel ler o arquivo /Users/marcelovasconcellos/Projects/emensageria/arquivos/eventos/esocial/ID1069287900001562021062020564500001.xml.
```
Encontrei referências a este diretório **/Users/marcelocasconcellos** no `config/settings.py` e em arquivos de migrations.

**Comment by marcelomdevasconcellos** [comment]
É necessário alterar as configurações na aba configurações, link configurações. Altere a variável FILES_PATH (esta pasta deverá possuir permissão de escrita no servidor). Mas sugiro verificar as demais variáveis.

**Comment by marcelomdevasconcellos** [comment]
Já fiz um Push retirando as referências do settings.py .. no caso nas migrations, não precisa se preocupar... isso foi corrigido nas ultimas atualizações.
